export { Feed } from "./feed/feed";
export { Login } from "./login/login";
export { Register } from "./register/register";
export { CampaingPage } from "./campaing-page/campaing-page";
export { InterestPage } from "./interest-page/interest-page";
export { Profile } from "./profile/profile";
export { ErrorPage } from "./error-page/error-page";
export { SearchUser } from "./search-user/search-user";
export { AnimalPage } from "./animal-page/animal-page";
